# Generated by Django 3.0.3 on 2020-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favory',
            name='tag',
            field=models.CharField(default='Non classé', max_length=200),
        ),
    ]
